# Generated by Django 5.1.15 on 2026-09-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorador',
            name='capacidad_deposito_l',
            field=models.FloatField(default=60.0, verbose_name='Capacidad del Depósito (Litros)'),
        ),
        migrations.AddField(
            model_name='explorador',
            name='consumo_medio_l_100km',
            field=models.FloatField(default=8.5, verbose_name='Consumo Medio (L/100km)'),
        ),
    ]
