# Generated by Django 5.1.15 on 2026-09-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploradores', '0002_explorador_capacidad_deposito_l_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorador',
            name='tipo_combustible',
            field=models.CharField(choices=[('gasoleo_a', 'Diésel / Gasóleo A'), ('gasolina_95', 'Gasolina 95 E5'), ('gasolina_98', 'Gasolina 98 E5'), ('glp', 'GLP / Autogás')], default='gasoleo_a', max_length=20, verbose_name='Tipo de Combustible'),
        ),
    ]
