# Generated by Django 5.1.15 on 2026-09-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploradores', '0003_explorador_tipo_combustible'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorador',
            name='codigo_postal',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Código Postal'),
        ),
    ]
