# Generated by Django 5.1.15 on 2026-09-07 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploradores', '0004_explorador_codigo_postal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('seguimiento', '🤝 Nuevo Compañero de Ruta / Seguidor'), ('comentario', '💬 Comentario en tu publicación'), ('reaccion', '🔥 Reacción a tu vivencia'), ('trofeo', '🏆 Trofeo Desbloqueado'), ('grupo', '🏕️ Grupo / Comunidad'), ('sistema', 'ℹ️ Notificación del Sistema')], default='sistema', max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('enlace', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('usuario_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Emisor')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
