# Generated by Django 5.1.15 on 2026-09-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploradores', '0005_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorador',
            name='recibio_bienvenida',
            field=models.BooleanField(default=False, verbose_name='Recibió Notificaciones de Bienvenida'),
        ),
    ]
