# Generated by Django 5.1.15 on 2026-09-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploradores', '0006_explorador_recibio_bienvenida'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorador',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código de Verificación'),
        ),
        migrations.AddField(
            model_name='explorador',
            name='email_verificado',
            field=models.BooleanField(default=False, verbose_name='Email Verificado'),
        ),
        migrations.AddField(
            model_name='explorador',
            name='fecha_codigo_verificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Envío Código'),
        ),
    ]
