# Generated by Django 5.1.15 on 2026-09-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploradores', '0007_explorador_codigo_verificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorador',
            name='notif_email_comentarios',
            field=models.BooleanField(default=True, verbose_name='Recibir email en comentarios'),
        ),
        migrations.AddField(
            model_name='explorador',
            name='notif_email_reacciones',
            field=models.BooleanField(default=True, verbose_name='Recibir email en reacciones'),
        ),
        migrations.AddField(
            model_name='explorador',
            name='notif_email_taller',
            field=models.BooleanField(default=True, verbose_name='Recibir email en aprobaciones/rechazos del taller'),
        ),
    ]
