# Generated by Django 5.1.15 on 2026-09-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploradores', '0008_explorador_notif_email_comentarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('seguimiento', '🤝 Nuevo Compañero de Ruta / Seguidor'), ('comentario', '💬 Comentario en tu publicación'), ('reaccion', '🔥 Reacción a tu vivencia'), ('trofeo', '🏆 Trofeo Desbloqueado'), ('grupo', '🏕️ Grupo / Comunidad'), ('sistema', 'ℹ️ Notificación del Sistema'), ('taller', '🛠️ Taller Camplink')], default='sistema', max_length=30),
        ),
    ]
