# Generated by Django 6.1.1 on 2026-09-14 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploradores', '0009_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuscripcionWebPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True, verbose_name='Endpoint Push')),
                ('p256dh', models.TextField(verbose_name='Clave p256dh')),
                ('auth', models.TextField(verbose_name='Clave Auth')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones_push', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción Web Push',
                'verbose_name_plural': 'Suscripciones Web Push',
            },
        ),
    ]
