# Generated by Django 5.1.15 on 2026-09-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploradores', '0010_suscripcionwebpush'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorador',
            name='notif_email_seguidos',
            field=models.BooleanField(default=True, verbose_name='Recibir email en publicaciones de seguidos'),
        ),
        migrations.AddField(
            model_name='explorador',
            name='notif_push_comentarios',
            field=models.BooleanField(default=True, verbose_name='Recibir push en comentarios'),
        ),
        migrations.AddField(
            model_name='explorador',
            name='notif_push_reacciones',
            field=models.BooleanField(default=True, verbose_name='Recibir push en reacciones'),
        ),
        migrations.AddField(
            model_name='explorador',
            name='notif_push_seguidos',
            field=models.BooleanField(default=True, verbose_name='Recibir push en publicaciones de seguidos'),
        ),
        migrations.AddField(
            model_name='explorador',
            name='notif_push_taller',
            field=models.BooleanField(default=True, verbose_name='Recibir push en aprobaciones del taller'),
        ),
    ]
