# Generated by Django 5.1.15 on 2026-09-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título del Artículo')),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True, verbose_name='Slug URL')),
                ('categoria', models.CharField(choices=[('supervivencia', 'Supervivencia y Acampada'), ('tecnologia_offline', 'Servidores Multimedia y Tecnología Offline'), ('electricidad', 'Baterías, Placas Solares y Electricidad'), ('mantenimiento_pro', 'Mantenimiento Avanzado del Vehículo'), ('rutas_secretas', 'Rutas Escondidas y Consejos Nómadas')], default='supervivencia', max_length=40, verbose_name='Categoría')),
                ('resumen', models.TextField(verbose_name='Resumen Corto')),
                ('contenido', models.TextField(verbose_name='Contenido Completo en Markdown o Texto')),
                ('imagen_cabecera', models.ImageField(blank=True, null=True, upload_to='guia/', verbose_name='Imagen Principal')),
                ('destacado', models.BooleanField(default=False, verbose_name='¿Destacado en Portada?')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artículo de la Guía del Nómada',
                'verbose_name_plural': 'Artículos de la Guía del Nómada',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='Respuesta / Aportación')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='taller_respuestas/', verbose_name='Archivo Adjunto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TemaTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('bricolaje', 'Bricolaje y Camperización'), ('piezas_3d', 'Piezas 3D y Modelos STL')], default='mantenimiento', max_length=30, verbose_name='Sección')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título del Tema')),
                ('descripcion', models.TextField(verbose_name='Explicación Detallada')),
                ('archivo_stl', models.FileField(blank=True, null=True, upload_to='taller_3d/', verbose_name='Archivo 3D (.stl para soportes, cierres, adaptadores)')),
                ('imagen_adjunta', models.ImageField(blank=True, null=True, upload_to='taller_fotos/', verbose_name='Foto Demostrativa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tema del Taller Nómada',
                'verbose_name_plural': 'Temas del Taller Nómada',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
