# Generated by Django 5.1.15 on 2026-09-07 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articuloguia',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos_guia', to=settings.AUTH_USER_MODEL, verbose_name='Autor (Administrador)'),
        ),
        migrations.AddField(
            model_name='respuestataller',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_taller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temataller',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas_taller', to=settings.AUTH_USER_MODEL, verbose_name='Explorador'),
        ),
        migrations.AddField(
            model_name='respuestataller',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='comunidad.temataller'),
        ),
    ]
