# Generated by Django 5.1.15 on 2026-09-10 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre de la Categoría')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True, verbose_name='Slug')),
                ('icono', models.CharField(default='Wrench', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(default='#3B82F6', max_length=30, verbose_name='Color Badge')),
                ('descripcion', models.CharField(blank=True, default='', max_length=250, verbose_name='Descripción')),
                ('es_fija', models.BooleanField(default=False, verbose_name='¿Es Fija del Sistema?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categosía de Publicación',
                'verbose_name_plural': 'Categorías de Publicaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='articuloguia',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.AlterModelOptions(
            name='temataller',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterField(
            model_name='articuloguia',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos_guia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articuloguia',
            name='categoria',
            field=models.CharField(choices=[('supervivencia', 'Supervivencia y Acampada'), ('tecnologia_offline', 'Servidores Multimedia y Tecnología Offline'), ('electricidad', 'Baterías, Placas Solares y Electricidad'), ('mantenimiento_pro', 'Mantenimiento Avanzado del Vehículo'), ('rutas_secretas', 'Rutas Escondidas y Consejos Nómadas')], default='supervivencia', max_length=40),
        ),
        migrations.AlterField(
            model_name='articuloguia',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articuloguia',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articuloguia',
            name='imagen_cabecera',
            field=models.ImageField(blank=True, null=True, upload_to='guia/'),
        ),
        migrations.AlterField(
            model_name='articuloguia',
            name='resumen',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articuloguia',
            name='slug',
            field=models.SlugField(blank=True, max_length=260, unique=True),
        ),
        migrations.AlterField(
            model_name='articuloguia',
            name='titulo',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='respuestataller',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='taller_respuestas/'),
        ),
        migrations.AlterField(
            model_name='respuestataller',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='respuestataller',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resppestas', to='comunidad.temataller'),
        ),
        migrations.AlterField(
            model_name='temataller',
            name='archivo_stl',
            field=models.FileField(blank=True, null=True, upload_to='taller_3d/'),
        ),
        migrations.AlterField(
            model_name='temataller',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas_taller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temataller',
            name='categoria',
            field=models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('bircolaje', 'Bricolaje y Camperización'), ('piezas_3d', 'Piezas 3D y Modelos STL')], default='mantenimiento', max_length=30),
        ),
        migrations.AlterField(
            model_name='temataller',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='temataller',
            name='imagen_adjunta',
            field=models.ImageField(blank=True, null=True, upload_to='taller_fotos/'),
        ),
        migrations.AlterField(
            model_name='temataller',
            name='titulo',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='PublicacionTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título de la Publicación')),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True, verbose_name='Slug')),
                ('resumen', models.TextField(verbose_name='Resumen Corto')),
                ('contenido', models.TextField(verbose_name='Contenido Detallado')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='taller_portadas/', verbose_name='Imagen Principal')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace de Video (YouTube / TikTok)')),
                ('archivo_descargable', models.FileField(blank=True, null=True, upload_to='taller_archivos/', verbose_name='Archivo Descargable (.STL, PDF, planos)')),
                ('enlace_externo', models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace Externo de Referencia')),
                ('enlace_externo_texto', models.CharField(blank=True, default='', max_length=120, verbose_name='Texto del Enlace')),
                ('es_guia_oficial', models.BooleanField(default=False, verbose_name='¿Es Guía Oficial?')),
                ('destacado', models.BooleanField(default=False, verbose_name='»Destacado en Portada?')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobado', 'Aprobado y Público'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('motivo_rechazo', models.TextField(blank=True, default='', verbose_name='Motivo de Rechazo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_taller', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones', to='comunidad.categoriapublicacion', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Publicación del Taller Camplink',
                'verbose_name_plural': 'Publicaciones del Taller Camplink',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenGaleriaPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='taller_galeria/', verbose_name='Foto Galería')),
                ('pie_de_foto', models.CharField(blank=True, default='', max_length=200, verbose_name='Pie de foto')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='comunidad.publicaciontaller', verbose_name='Publicación')),
            ],
            options={
                'ordering': ['orden', 'fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='taller_comentarios_adjuntos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_taller', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='comunidad.publicaciontaller', verbose_name='Publicación')),
            ],
            options={
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
