# Generated by Django 6.1.1 on 2026-09-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0003_categoriapublicacion_alter_articuloguia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciontaller',
            name='imagen_principal_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL Externa de Imagen Principal (alternativa a subir archivo)'),
        ),
    ]
