# Generated by Django 5.1.15 on 2026-09-07 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Lugar')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('latitud', models.FloatField(verbose_name='Latitud GPS')),
                ('longitud', models.FloatField(verbose_name='Longitud GPS')),
                ('pais', models.CharField(default='España', max_length=100, verbose_name='País')),
                ('comunidad_autonoma', models.CharField(blank=True, default='', max_length=100, verbose_name='Comunidad Autónoma')),
                ('provincia', models.CharField(blank=True, default='', max_length=100, verbose_name='Provincia')),
                ('poblacion', models.CharField(blank=True, default='', max_length=100, verbose_name='Población')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Precio (€/noche)')),
                ('es_gratuito', models.BooleanField(default=False, verbose_name='¿Es gratuito?')),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='lugares/', verbose_name='Foto Principal')),
                ('tiene_agua', models.BooleanField(default=False, verbose_name='Punto de Agua Potable')),
                ('tiene_lavabo', models.BooleanField(default=False, verbose_name='Lavabo / WC')),
                ('tiene_duchas', models.BooleanField(default=False, verbose_name='Duchas')),
                ('tiene_electricidad', models.BooleanField(default=False, verbose_name='Toma de Electricidad')),
                ('tiene_vaciado_aguas_grises', models.BooleanField(default=False, verbose_name='Vaciado de Aguas Grises')),
                ('tiene_vaciado_aguas_negras', models.BooleanField(default=False, verbose_name='Vaciado de Aguas Negras (WC químico)')),
                ('admite_mascotas', models.BooleanField(default=True, verbose_name='Admite Mascotas')),
                ('tiene_wifi', models.BooleanField(default=False, verbose_name='Acceso WiFi')),
                ('tiene_mesas_picnic', models.BooleanField(default=False, verbose_name='Mesas de Picnic')),
                ('es_zona_recreativa', models.BooleanField(default=False, verbose_name='Zona Recreativa')),
                ('tiene_senderos_sencillos', models.BooleanField(default=False, verbose_name='Senderos Sencillos de Paseo')),
                ('ideal_ninos_10_anos', models.BooleanField(default=False, verbose_name='Ideal para Niños de 10 Años')),
                ('apto_grandes_autocaravanas', models.BooleanField(default=True, verbose_name='Apto para Autocaravanas >7m')),
                ('permite_sacar_toldo', models.BooleanField(default=False, verbose_name='Permite Desplegar Toldo / Mesas')),
                ('valoracion_media', models.FloatField(default=5.0, verbose_name='Valoración Camper Media')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lugares_creados', to=settings.AUTH_USER_MODEL, verbose_name='Explorador Creador')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='FotoLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='lugares/galeria/')),
                ('pie_foto', models.CharField(blank=True, default='', max_length=200, verbose_name='Pie de Foto')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='lugares.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_camper', models.IntegerField(default=5, verbose_name='Puntuación Camper (1-5)')),
                ('comentario', models.TextField(verbose_name='Opinión del Explorador')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('explorador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_valoraciones_lugares', to=settings.AUTH_USER_MODEL)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='lugares.lugar')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
