# Generated by Django 5.1.15 on 2026-09-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='acceso_asfaltado',
            field=models.BooleanField(default=True, verbose_name='🛣️ Acceso Asfaltado'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='ideal_familias',
            field=models.BooleanField(default=False, verbose_name='👨\u200d👩\u200d👧\u200d👦 Ideal Familias (niños ~10 años)'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='mucha_sombra',
            field=models.BooleanField(default=False, verbose_name='🌲 Mucha Sombra'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='muy_soleado',
            field=models.BooleanField(default=False, verbose_name='☀️ Muy Soleado (Placas Solares)'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='playa_cercana',
            field=models.BooleanField(default=False, verbose_name='🏖️ Playa Cercana'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='rutas_en_bici',
            field=models.BooleanField(default=False, verbose_name='🚴 Rutas en Bici'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='terreno_nivelado',
            field=models.BooleanField(default=True, verbose_name='📐 Terreno Nivelado'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='tiene_basuras',
            field=models.BooleanField(default=False, verbose_name='🗑️ Basuras'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='tiene_senderismo',
            field=models.BooleanField(default=False, verbose_name='🥾 Senderismo'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='tipo_lugar',
            field=models.CharField(choices=[('pernocta_libre', '🌲 Pernocta Libre (Naturaleza)'), ('area_autocaravanas', '🚐 Área de Autocaravanas'), ('camping', '⛺ Camping'), ('parking_urbano', '🅿️ Parking Urbano / Mixto'), ('area_recreativa', '🏞️ Área Recreativa / Merendero'), ('solo_servicios', '💧 Solo Servicios')], default='pernocta_libre', max_length=40, verbose_name='Tipo de Lugar'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='admite_mascotas',
            field=models.BooleanField(default=True, verbose_name='🐕 Admite Mascotas'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='apto_grandes_autocaravanas',
            field=models.BooleanField(default=True, verbose_name='🚐 Apto para Autocaravanas >7m'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='permite_sacar_toldo',
            field=models.BooleanField(default=False, verbose_name='🪑 Permite Desplegar Toldo / Mesas'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='tiene_agua',
            field=models.BooleanField(default=False, verbose_name='🚰 Agua Potable'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='tiene_duchas',
            field=models.BooleanField(default=False, verbose_name='🚿 Duchas'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='tiene_electricidad',
            field=models.BooleanField(default=False, verbose_name='⚡ Electricidad'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='tiene_lavabo',
            field=models.BooleanField(default=False, verbose_name='🚽 Lavabos'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='tiene_vaciado_aguas_grises',
            field=models.BooleanField(default=False, verbose_name='🔄 Vaciado de Aguas Grises'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='tiene_vaciado_aguas_negras',
            field=models.BooleanField(default=False, verbose_name='🚽 Vaciado de Aguas Negras (WC químico)'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='tiene_wifi',
            field=models.BooleanField(default=False, verbose_name='🛜 Wi-Fi'),
        ),
    ]
