# Generated by Django 5.1.15 on 2026-09-08 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0002_lugar_acceso_asfaltado_lugar_ideal_familias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaPersonalLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True, default='', verbose_name='Nota Personal y Privada')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('explorador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_lugares', to=settings.AUTH_USER_MODEL, verbose_name='Explorador')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_personales', to='lugares.lugar', verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Nota Personal de Lugar',
                'verbose_name_plural': 'Notas Personales de Lugares',
                'unique_together': {('lugar', 'explorador')},
            },
        ),
    ]
