# Generated by Django 5.1.15 on 2026-09-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0003_notapersonallugar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notapersonallugar',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Nota Personal de Lugar', 'verbose_name_plural': 'Notas Personales de Lugares'},
        ),
        migrations.AlterUniqueTogether(
            name='notapersonallugar',
            unique_together=set(),
        ),
    ]
