# Generated by Django 5.1.15 on 2026-09-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0004_alter_notapersonallugar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracionlugar',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='valoraciones/', verbose_name='Foto de la Opinión'),
        ),
    ]
