# Generated by Django 6.1.1 on 2026-09-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0005_valoracionlugar_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='valoracion_media',
            field=models.FloatField(default=0.0, verbose_name='Valoración Camper Media'),
        ),
    ]
