# Generated by Django 5.1.15 on 2026-09-07 10:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trofeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código Único')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Trofeo')),
                ('descripcion', models.TextField(verbose_name='Descripción del Logro')),
                ('nivel', models.CharField(choices=[('madera', 'Madera'), ('bronce', 'Bronce'), ('plata', 'Plata'), ('oro', 'Oro'), ('platino', 'Platino')], default='madera', max_length=20, verbose_name='Nivel')),
                ('icono', models.CharField(default='camp-trophy', max_length=50, verbose_name='Icono Identificador')),
                ('requisito_tipo', models.CharField(choices=[('checkins', 'Número de Pernoctas / Check-ins'), ('km', 'Kilómetros Recorridos'), ('lugares', 'Lugares Creados'), ('platino', '100% de Todos los Trofeos')], max_length=30, verbose_name='Tipo de Requisito')),
                ('requisito_cantidad', models.IntegerField(default=1, verbose_name='Cantidad Necesaria')),
            ],
            options={
                'ordering': ['requisito_cantidad'],
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Ruta Nómada', max_length=200, verbose_name='Título del Viaje')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Diario del Viaje')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('esta_cerrado', models.BooleanField(default=False, verbose_name='¿Viaje Finalizado?')),
                ('km_totales', models.FloatField(default=0.0, verbose_name='Kilómetros Totales Recorridos')),
                ('comunidades_visitadas', models.JSONField(blank=True, default=list, verbose_name='Comunidades Autónomas')),
                ('paises_visitados', models.JSONField(blank=True, default=list, verbose_name='Países Visitados')),
                ('resumen_ruta', models.JSONField(blank=True, default=list, verbose_name='Resumen de Puntos y Coordenadas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('explorador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to=settings.AUTH_USER_MODEL, verbose_name='Explorador')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TrofeoExplorador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueo', models.DateTimeField(auto_now_add=True)),
                ('explorador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trofeos_conseguidos', to=settings.AUTH_USER_MODEL)),
                ('trofeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conseguido_por', to='viajes.trofeo')),
            ],
            options={
                'unique_together': {('explorador', 'trofeo')},
            },
        ),
    ]
