# Generated by Django 5.1.15 on 2026-09-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trofeoexplorador',
            name='es_destacado',
            field=models.BooleanField(default=False, verbose_name='¿Mostrar destacado en el perfil?'),
        ),
    ]
