# Generated by Django 5.1.15 on 2026-09-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_trofeoexplorador_es_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='trofeo',
            name='categoria',
            field=models.CharField(default='general', max_length=50, verbose_name='Código de Categoría'),
        ),
        migrations.AddField(
            model_name='trofeo',
            name='categoria_nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre de la Categoría'),
        ),
        migrations.AddField(
            model_name='trofeo',
            name='unidad',
            field=models.CharField(default='', max_length=30, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='trofeo',
            name='requisito_tipo',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Tipo de Requisito'),
        ),
    ]
