# Generated by Django 5.1.15 on 2026-09-11 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_trofeo_categoria_trofeo_categoria_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado de la invitación')),
                ('mensaje', models.TextField(blank=True, default='', verbose_name='Mensaje opcional')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_recibidas_viaje', to=settings.AUTH_USER_MODEL, verbose_name='Explorador destinatario')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_enviadas_viaje', to=settings.AUTH_USER_MODEL, verbose_name='Explorador que comparte')),
                ('viaje_copia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origen_invitacion', to='viajes.viaje', verbose_name='Viaje creado al aceptar')),
                ('viaje_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_enviadas', to='viajes.viaje', verbose_name='Viaje compartido')),
            ],
            options={
                'verbose_name': 'Invitación de Viaje',
                'verbose_name_plural': 'Invitaciones de Viaje',
                'ordering': ['-fecha_envio'],
                'unique_together': {('viaje_origen', 'destinatario')},
            },
        ),
    ]
