# Generated by Django on 2026-09-15

from django.db import migrations


def recalcular_trofeos_produccion(apps, schema_editor):
    try:
        from viajes.services import inicializar_catalogo_trofeos, verificar_y_desbloquear_trofeos
        from exploradores.models import Explorador
        from viajes.models import TrofeoExplorador

        # 1. Asegurar que el catálogo oficial de trofeos esté inicializado
        inicializar_catalogo_trofeos()

        # 2. Resetear todos los trofeos previamente asignados a 0
        TrofeoExplorador.objects.all().delete()

        # 3. Evaluar actividad real y desbloquear únicamente los trofeos ganados
        for explorador in Explorador.objects.all():
            verificar_y_desbloquear_trofeos(explorador)
    except Exception as e:
        print(f"Advertencia al ejecutar migración de recálculo de trofeos: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_invitacion_viaje'),
    ]

    operations = [
        migrations.RunPython(recalcular_trofeos_produccion, reverse_code=migrations.RunPython.noop),
    ]
