# Generated by Django 5.1.15 on 2026-09-07 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_llegada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Llegada / Pernocta')),
                ('dias_previstos', models.IntegerField(default=1, verbose_name='¿Cuántos días tienes pensado quedarte?')),
                ('valoracion_camper', models.IntegerField(default=5, verbose_name='Valoración Camper (1-5 🚐)')),
                ('comentario_publico', models.TextField(blank=True, default='', verbose_name='Comentario Público para el Diario')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='checkins/', verbose_name='Foto de la Pernocta')),
                ('notas_privadas', models.TextField(blank=True, default='', verbose_name='Notas Privadas (solo visibles para mí: estado del terreno, ruido, etc.)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Check-in de Pernocta',
                'verbose_name_plural': 'Check-ins de Pernocta',
                'ordering': ['-fecha_llegada'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Texto del Diario')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='diario/', verbose_name='Foto de la Ruta')),
                ('visibilidad', models.CharField(choices=[('publico', 'Público (Toda la Comunidad)'), ('seguidores', 'Solo Exploradores Seguidos'), ('grupo_privado', 'Grupo Privado')], default='publico', max_length=20, verbose_name='Nivel de Privacidad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Publicación de Ruta',
                'verbose_name_plural': 'Publicaciones de Ruta',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
