# Generated by Django 5.1.15 on 2026-09-07 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diario', '0001_initial'),
        ('exploradores', '0001_initial'),
        ('lugares', '0001_initial'),
        ('viajes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='explorador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL, verbose_name='Explorador'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='lugares.lugar', verbose_name='Lugar de Pernocta'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_asociados', to='viajes.viaje', verbose_name='Viaje Vinculado'),
        ),
        migrations.AddField(
            model_name='comentariopublicacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL, verbose_name='Explorador'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='grupo_privado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_grupo', to='exploradores.grupoprivacidad', verbose_name='Grupo Seleccionado'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_mencionan', to='lugares.lugar', verbose_name='Lugar Relacionado'),
        ),
        migrations.AddField(
            model_name='comentariopublicacion',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='diario.publicacion'),
        ),
    ]
