# Generated by Django 5.1.15 on 2026-09-07 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaccionPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fuego', '🔥 Buena ruta'), ('pino', '🌲 Guardado para ir'), ('alerta', '⚠️ Ojo con el acceso')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='diario.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones_diario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reacción de Publicación',
                'verbose_name_plural': 'Reacciones de Publicaciones',
                'unique_together': {('publicacion', 'usuario', 'tipo')},
            },
        ),
    ]
