# Generated by Django 5.1.15 on 2026-09-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0003_reaccionpublicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='valoracion_camper',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='Valoración Camper (1-5 🚐)'),
        ),
    ]
